# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [3]:
import numpy as np
# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]

# OUTPUT: [16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
# 22.06222222]

height1= np.array(height)
weight1= np.array(weight)

formula = weight1 / (height1**2)
formula1 = formula * 730

print(formula1)



array([16.86620458, 17.87755102, 18.82562984, 19.71450617, 20.54794521,
       21.32943755, 22.06222222])

### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [9]:
"""
Example Result
array([[14.21633515,  7.98846653,  9.64140715],
       [ 6.30982234,  9.96414331,  8.43153688],
       [14.73102068, 11.76072894, 14.23356121]])
"""

def makeMatrix(low, high, shape = (3,3), data_type = float):
    return np.random.uniform(low, high, shape).astype(data_type)

print(makeMatrix(0, 10, (4,4), float))


[[6.98649133 7.12000656 2.97807533 7.29415925]
 [4.63044599 0.12100106 3.97796937 1.80027301]
 [1.00844893 1.54367672 8.09619442 5.3998093 ]
 [4.81042969 4.31044998 1.46835386 9.91467433]]


NameError: name 'np' is not defined

### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [ ]:
import csv
import numpy as np

#Test to make sure you have the correct data



In [11]:
"""
Example Result - Not the actual result
Boston 18 had more SLG in 2018
[0.404 0.443 0.392 0.403 0.482 0.424 0.402 0.459 0.429 0.354 0.387 0.333
 0.539 0.243 0.262 0.354 0.342 0.339 0.328 0.306 0.222 0.2   1.   ]
"""

FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray

# loading
def load_data(filepath, d = ','):
    data = np.genfromtxt(filepath, delimiter = d, skip_header = 1,
                        usecols = np.arange(0,23), invalid_raise = False,
                        names = FIELDS, dtype = DATATYPES)
    return data

bs2017 = load_data('../files/redsox_2017_hitting.txt')
bs2018 = load_data('../files/redsox_2018_hitting.txt')

#get the stuff
slg_17 = np.array(bs2017["SLG"])
slg_18 = np.array(bs2018["SLG"])

avg_17 = sum(slg_17) / len(slg_17)
print(f'2017 average SLG was: {avg_17}')
avg_18 = sum(slg_18) / len(slg_18)
print(f'2018 average SLG was: {avg_18}')

# looks like 2017 has 






2017 average SLG was: 0.39334782374941785
2018 average SLG was: 0.38750000335276125
